### ISSUE TITLE
A question in code

### ISSUE THREAD

**Issue by aatiqa-ghazali** [smiler96/Image-Super-Resolution#1]
Hi thanku for providing these codes.
I just want to ask that in the implementation of HAN model in your code CSAM module is different but in author's code the part which you have used in your code is commented. So which approach should we use in implementation.

**Comment by smiler96** [comment]
> Hi thanku for providing these codes. I just want to ask that in the implementation of HAN model in your code CSAM module is different but in author's code the part which you have used in your code is commented. So which approach should we use in implementation.

please follow the author's code.

**Comment by aatiqa-ghazali** [comment]
I am implementing this model is tensor-flow .The code that authors have used in this module is not working that's why I asked you. Anyways Thank you Sir @smiler96  for your response.

**Comment by smiler96** [comment]
> I am implementing this model is tensor-flow .The code that authors have used in this module is not working that's why I asked you. Anyways Thank you Sir @smiler96 for your response.

you are welcome. I think that if you use this code in my repository, you can have an explanation that is the difference between the  origin paper.
